apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
stringData:
  mysql-root-password: example
  mysql-user-password: wordpress
  mysql-user: wordpress
  mysql-password: wordpress
  mysql-database: wordpress
